Status.create(name: 'New', color: 'primary')
Status.create(name: 'In progress', color: 'success')
Status.create(name: 'Complete', color: 'light')
Label.create(name: 'Urgent', color: "primary")
Label.create(name: 'home', color: "success")
